### ISSUE TITLE
[SUGESTÃO] Adicionar convenção de commits no CONTRIBUTING.MD

### ISSUE THREAD

**Issue by Limagn** [Arthu-RL/FuturoFinanceiro#18]
**Sugestão está relacionada a um problema?**
Não

**Descrição da solução.**
Adicionar informações referentes a padronização das mensagens dos commits no [CONTRIBUTING](https://github.com/Arthu-RL/SimuladorInvestimentoWeb/blob/main/CONTRIBUTING.md) no item 5.

**Descrição da alternativa considerada.**
Inserir uma tabela demonstrando os tipos de commits existentes em convenção e uma descrição a respeito do seu uso.

**Contexto adicional**

*Exemplo:*

#### Convenção de Commits 

| Tipo de Commit |                             Descrição                                | Exemplo
| ---------------|----------------------------------------------------------------------|-----------
| `feat`         | Adiciona uma nova funcionalidade ao projeto.                         | `feat: add achievements modal`
| `fix`          | Corrige um bug ou problema no projeto.                               | `fix: disable simulator at home page`
| `docs`         | Altera a documentação do projeto.                                    | `docs: update README.md`
| `style`        | Realiza mudanças na aparência, sem alterar a funcionalidade.         | `style: reduce achievement toast size`
| `refactor`     | Realiza mudanças no código que não alteram a funcionalidade.         | `refactor: improve some namings in 'useAssetColumns'`
| `test`         | Adiciona ou modifica testes no projeto.                              | `test: add unit test for UserService`
| `chore`        | Atualização de tarefas que não ocasionam alteração no código de produção, mas mudanças de ferramentas, mudanças de configuração e bibliotecas que realmente não entram em produção                                        | `chore: increase favicon size`

**Comment by RGomes98** [comment]
PR aceito
